### ISSUE TITLE
[Feature] 로그인 및 회원가입 페이지 구현

### ISSUE THREAD

**Issue by yonghyeun** [dogandme/frontend#12]
### 목적

피그마에 작성된 디자인에 따라 페이지를 생성하고 다음과 같은 기능들이 정상 작동 하는지 확인하기 위함

- 소셜 로그인 (네이버 , 구글)
- 일반 로그인 (회원가입 시 사용한 이메일)

현재의 이슈의 기능은 본 개발 내용에 포함되지 않을 수 있음

#### 공통 : 컴포넌트들의 기본 기능 

-  [x] password input 부분에서 눈 아이콘 클릭 시 password가 가려지지 않고 나타난다.

#### 회원가입 : 유저의 정보가 DB에 존재하지 않은 상황에서 

- 각 로그인 절차에 맞춰 
  - [ ] GNB 하단에 존재하는 status-bar는 1,2,3 단계에 맞춰 progress bar 가 변경된다.

- 유저가 소셜 로그인 버튼을 클릭하고 소셜 로그인에 성공하면
  - [ ] 회원가입 두 번째 절차인 기본 회원 정보 입력 페이지로 이동한다.  (백엔드단의 처리 필요)

- 유저가 이메일로 회원가입 버튼을 클릭하면 
  - [x] 회원가입 첫 번째 절차인  이메일로 회원가입 페이지로 이동한다.
  
-  회원가입 첫 번째 페이지에서 모든 인풋 필드는 
  - [ ] 모든 인풋 필드의 유효성이 만족해야지만 다음 버튼을 활성화 된다.
  - [ ] 인풋 필드는 유효성을 만족하지 않으면  배경색이 변경되고 주의 문구가 나타난다.
  - [ ] 인풋 필드는 포커스 되면 배경색이 변경된다. 

- 회원가입 첫 번째 페이지에서 이메일 인풋 필드는
  - [ ] 이메일 입력에서 코드전송 버튼은 이메일 입력버튼의 유효성이 만족해야지만 활성화 된다. 
  - [ ] 코드 전송 결과 중복된 이메일이라면 이메일 입력 인풋 필드에 중복 이메일 문구가 표기된다.
  - [ ] 코드 전송 결과 중복된 이메일이라면 코드 전송 버튼은 비활성화 된다. 
  - [ ] 동일한 이메일 주소로 코드 전송 버튼이 1분 이내에 클릭되면 코드 전송이 일어나지 않는다.
  - [ ] 동일한 이메일 주소로 코드 전송 버튼이 1분 이내에 클릭되면 1분 이후 재전송 해달라는 모달창이 발생한다. 
  - [ ] 코드 전송이 정상적으로 일어나면 인증 코드 입력 필드가 활성화 된다.  
  - [ ] 인증 코드 입력 란에서 서버에서 인증한 이메일이 아닐 경우 인증코드를 다시 확인해주세요 문구가 주의 문구로 작성된다. 
 
-  회원가입 첫 번째 페이지에서 비밀번호 인풋 필드는
  - [ ] 비밀번호 인풋 필드는 유효성을 만족하지 않으면 주의 문구와 함께 배경색이 변경된다.  
  - [ ] 비밀번호 인풋 필드에서 비밀번호 입력 , 비밀번호 확인 인풋 필드의 유효성이 서로 다를 경우 다르게 렌더링 된다.  
  - ![image](https://github.com/user-attachments/assets/3fc5ec52-ae9d-4cb1-a93c-afc538dd79ec)
 

#### 로그인

- 유저가 소셜 로그인을 시도 할 때 
  - [x] 모든 인풋 필드가 입력되지 않았을 경우 로그인 버튼은 활성화 되지 않는다.

- 유저가 소셜 로그인을 시도 했을 때 유저가 소셜 로그인에 성공하면  
  - [x] 가장 최근 접근한 탭으로 넘어가거나 `/` 경로로 리다이렉션 된다. 
  - [x] 쿠키에 토큰 정보를 저장한다.
  - [ ] 토큰을 메모리에 저장한다. 

- 유저가 소셜 로그인을 시도 했을 때 
  - [ ] 회원 정보가 맞지 않으면 다시 확인하라는 모달창이 뜬다.
  - [ ] 네트워크 오류가 발생하면 잠시 후 다시 이용해달라는 모달창이 뜬다.

**Comment by yonghyeun** [comment]
### 08/17 작업사항 요약 

- `react-router-dom` 으로 기본적인 라우터 구조와 레이아웃 구조 생성 
- `/auth` 페이지에서 `google` oauth 를 이용햔 회원가입 백엔드와 소통하여 기능 생성 완료 , 소셜 로그인이 성공하면 백엔드단에서 두 번째 회원가입 페이지로 리다이렉션 응답 보내주기로 하였음 (현재 회원 가입 페이지는 존재하지 않아 임의의 경로로 테스트 해봄 , 쿠키에 토큰 잘 저장 됨)
- `/auth/login` 페이지 기능 일부 완료 
  - 해당 페이지는 이메일로 로그인 페이지이며 백엔드와 소통하는 기능은 존재함 , 다만 해당 부분 백엔드와 테스트 진행하지 않았기에 테스트 필요함 
  - 이메일 , 패스워드 인풋 부분 `onFocus , onBlur` 이벤트 핸들러 이용하여 상단 `div` 태그의 `border` 색상 변경
    - 직접 `input` 태그의 `border` 색을 변경하지 않은 이유는 패스워드 인풋 부분에서 `input` 태그와 함께 다른 컴포넌트를 렌더링 해야 했기 떄문임,  이 방법이 적절한 방법인지 잘 모르겠음 
    
    
디자인 토큰이 나오지 않은 마당에 너무 쓸데없이 많이 작업해서 똑같은 일을 두 번 하게 만든 거 같아서 마음이 무거움 .. 

회원 가입 페이지를 작업하지 않은 이유는 만들어둔걸 고치는게 더 어려운 작업일 거 같았기 때문이며 추가로 피그마에서 회원가입 페이지의 컴포넌트 계층이 명확하지 않아 해당 부분을 임의로 수정 할 경우 디자이너가 원하는 방향과 다를 가능성이 존재했기 때문 

###  TODO 

- 디자인 토큰 보고 다시 재개발 
- 스파게티처럼 꼬여있는 코드들 리팩토링 및 파일 컨벤션 재확립 , FSD 구조를 이용했으나 오히려 더 보기 힘든듯한 느낌 .. 컴포넌트를 하나하나 만들어야 하나 ? 파일명 컨벤션을 정해둬야 할 거 같음 ..
- 각 로직 유효성 검증 및 유효성에 따른 에러 메시지 렌더링 
- 회원 가입 페이지 
- svg와 같은 파일들을 어떻게 관리해야 할지 잘 모르겠음 , svgr 라이브러리를 설치해서 컴포넌트처럼 사용하는 방법도 있다는데 흠 .. 

ps. 짧은 개발 시간이기에 TDD 는 포기하고 에러가 발생하거나 대규모 리팩토링 시행하는 경우에만 테스트를 할까 하는 마음이 들기도 함 .. ui 테스트 용으로 스토리북만 좀 쓸까 싶음
