### ISSUE TITLE
[Feature] 탈퇴하기 API 요청 붙이기

### ISSUE THREAD

**Issue by yonghyeun** [dogandme/frontend#303]
### 목적- 추가하고자 하는 기능을 설명해주세요

![image](https://github.com/user-attachments/assets/9e4bf57c-7408-4107-b72c-53d5f1584404)

해당 폼에서 탈퇴하기 요청에 대한 API 요청을 보내도록 한다. 

#### TODO 

- [x] 핸들러 작성
- [x] 탈퇴하기 폼 리팩 토링
- [x] useMutataion 을 이용한 API 요청 생성 
- [x] 탈퇴하기 폼에서 사용 되는 ExitConfirmModal 스타일 수정
- [x] mutation 진행 중엔 모달이 닫히지 않도록 하기
